#!/bin/bash

# Colors
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

function error_message {
  echo -e "${RED}$1${NC}"
  exit 1
}

#Sync scrip compares fales that are not equal or dont exist
sync()
{
find $1 -type f -follow -print | while read file1
  do
  ssh $2 mkdir -p $(dirname $file1) 
    if ssh $2 stat $file1 \> /dev/null 2\>\&1
      then
      echo -e "${YELLOW}file exists checking md5sum...${NC}"
      md5sum1=$( md5sum $file1 | awk '{print $1;}' )
      md5sum2=$( ssh $2 md5sum $file1 | awk '{print $1;}' )
      if [ "$md5sum1" != "$md5sum2" ]
        then
          scp -r $1 $2:$file1
          echo -e "${GREEN} not equal files have been copied ${NC}"
        else
          echo -e "${YELLOW}file does not exist${NC}"
          scp -r $1 $2:$file1
          echo -e "${GREEN} absent files have been copied ${NC}"
      fi
      else 
      echo -e "${YELLOW}file does not exist${NC}"
      scp -r $1 $2:$file1
      echo -e "${GREEN} absent files have been copied ${NC}"
    fi
  done
}
trap ctrl_c INT
if [ $# -lt 1 ]
  then
    error_message "invalid arg"
fi

case $1 in
  --sync)
    if [ $# -lt 3 ]
      then
        error_message "not enough args see --help more information"
    fi
    if [ ! -f "$2" ] && [ ! -d "$2" ] ; then
    error_message "file or directory not founid"
    fi
    for i in $(echo $3 | sed "s/,/ /g")
      do
      if ! nc -z -v -w5 $i 22
        then
          error_message "server is not avaliable on port 22"
      fi
        sync $2 $i &
      done
    wait
    ;;
  --help)
    echo help
    ;;
  *)
    error_message "invalid arg --help"
    ;;
esac
